### ISSUE TITLE
Fatal error: Uncaught Voronkovich\SberbankAcquiring\Exception\ActionException: Access denied

### ISSUE THREAD

**Issue by bigcrazzy** [voronkovich/sberbank-acquiring-client#14]
Почему то все время получаю такую ошибку, не подскажете куда смотреть

**Comment by zavod008** [comment]
Подсказка для будущих искателей.
Если тестовые логин и пароль верны, то поставьте в параметре 'apiUri' => Client::API_URI_TEST.
