### ISSUE TITLE
добавить публичный метод получени apiUrl

### ISSUE THREAD

**Issue by vladimirovii** [voronkovich/sberbank-acquiring-client#16]
Просьба добавить публичный метод получени apiUrl.
Описание ситуации:
В DI определяю тестовое окружение клиента.
Агрегирую клиента в сервис, пишу метод получения URL для редиректа на оплату (ситуация когда заказ уже был зарегистрирован ранее, сейчас требуется повторно сделать редирект на страницу оплаты), я не могу получить окружение клиента (тестовое или боевое) приходится еще в одном месте определять окружение...

Заранее спасибо за ответ.

**Comment by voronkovich** [comment]
@vladimirovii, Я думаю вы сделали правильно. Я бы сделал чуть-чуть по другому - создал бы обёртку для клиента:

```php
<?php

namespace App;

use Voronkovich\SberbankAcquiring\Client;

class Sberbank
{
    public const TEST = 'test';
    public const PROD = 'prod';

    private $env;
    private $client;

    public function __construct(string $env, array $options)
    {
        if (isset($options['apiUri'])) {
            throw new \InvalidArgumentException('Don\'t set "apiUri" manually.');
        }

        switch ($env) {
            case self::PROD:
                $options['apiUri'] = Client::API_URI;
                break;
            case self::TEST:
                $options['apiUri'] = Client::API_URI_TEST;
                break;
            default:
                throw new \InvalidArgumentException(\sprintf('Invalid environment: "%s".', $env));
                break;
        }

        $this->env = $env;
        $this->client = new Client($options);
    }

    public function isTest(): bool
    {
        return self::TEST === $this->env;
    }

    public function isProd(): bool
    {
        return self::PROD === $this->env;
    }

    public function registerOrder($orderId, int $amount, string $returnUrl, array $data = []): array
    {
        return $this->client->registerOrder($orderId, $amount, $returnUrl, $data);
    }
}
```

**Comment by voronkovich** [comment]
@vladimirovii, можно закрывать тему? Или вам всё-таки нужен публичный метод для получения URL? Если нужен - делайте пулл-реквест, только сделайте тогда публичные методы для получения всех настроек (getUserName, getToken, getApiUri и т.д.)

**Comment by vladimirovii** [comment]
давайте сделаем публичный метод))
Дело в том что есть принципиальная разница между, тем что бы создать Клиента
`new \Voronkovich\SberbankAcquiring\Client($options)`
и агрегировать его
`
$container->setSingleton(\Voronkovich\SberbankAcquiring\Client::class, [
            [
                'userName' => 'login',
                'password' => 'pwd
            ]
        ]);
class Sberbank
{
    private $client;

    public function __construct(\Voronkovich\SberbankAcquiring\Client $client)
    {
        $this->client = $client
    }
}
`

**Comment by voronkovich** [comment]
@vladimirovii, Ok, тогда создавайте пулл-реквест. Только, как я уже я и писал выше, сделайте геттеры для всех свойств.
