### ISSUE TITLE
Корзина товаров

### ISSUE THREAD

**Issue by IvanTyumikov** [voronkovich/sberbank-acquiring-client#19]
Здравствуйте, подскажите, пожалуйста, я могу передавать корзину товаров с помощью запроса registerOrder? (через параметр $orderBundle)

**Comment by IvanTyumikov** [comment]
И такое формирование корзины товаров, в целом, правильное?
`$cart = $_SESSION['tsvshopfin']['orders'];
	$positionId=0;
	foreach ($cart as $item) {
		$items[] = array(
			'positionId' => $positionId,
			'name' => $item['name'],
			'quantity' => array(
				 'value' => $item['qty'],
				 'measure' => 'шт.',
			 ),
			'itemCode' => $item['url'],
			'itemPrice' => $item['price'],
			'tax' => array(
				 'taxType' => 0,
				 'taxSum' => 0,
			 ),
			'itemAttributes' => array(
				 'paymentMethod' => 1,
				 'paymentObject' => 1,
			 ),
		);
		$positionId++;
	}
	
	$cartItems = array('items'=>$items);
	$orderBundle = array('cartItems' => $cartItems);`

**Comment by ishapkin** [comment]
Нужно отправлять по аналогии с GET-запросом

https://3dsec.sberbank.ru/payment/rest/register.do?userName=test-api&password=PASSWORD&amount=150000&orderNumber=102131&returnUrl=https://ya.ru&description=скидка&orderBundle={"customerDetails":{"email":"test@test.ru","passport":"2222444444","fullName":"Иванов Ivan","phone":"+77777777777"},"cartItems":{"items":[{"positionId":"1","name":"order bundle item","itemDetails":{"itemDetailsParams":[{"value":"Размер: 140х200, Цвет: Дуб белый, Материал: Сосна, Высота: 300","name":"Торговое предложение"}]},"quantity":{"value":1,"measure":"skgjb.ком"},"itemCode":"2525-46464646","tax":{"taxType":3,"taxSum":25000},"itemPrice":150000,"discount":{"discountType":"просто скидка","discountValue":"10"},"agentInterest":{"interestType":"агентская комиссия","interestValue":"10"},"itemAttributes":{"attributes":[{"name":"paymentMethod","value":"1"},{"name":"paymentObject","value":"1"}]}}]}}
Подробнее о передаче товарной корзины по ссылке: 
https://securepayments.sberbank.ru/wiki/doku.php/integration:api:rest:requests:register_cart

**Comment by voronkovich** [comment]
@IvanTyumikov, да, можете. Пример есть тут: https://github.com/voronkovich/sberbank-acquiring-client/issues/8

**Comment by IvanTyumikov** [comment]
@voronkovich, спасибо большое. Разобрался.
