### ISSUE TITLE
Fatal error at src/Client.php:300 in PHP before 5.5

### ISSUE THREAD

**Issue by maderwin** [voronkovich/sberbank-acquiring-client#2]
> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

http://php.net/manual/en/function.empty.php

**Comment by voronkovich** [comment]
@maderwin, thanks for the reporting this bug. I've fixed it by using the `count` function instead the `empty`. Run `composer update` to get a new release.
