### ISSUE TITLE
ApiError 4

### ISSUE THREAD

**Issue by HamasakiBrain** [voronkovich/sberbank-acquiring-client#23]
ApiError Object ( [code] => 4 [message] => Неверный формат запроса [fields] => ) 

`$params['orderBundle'] = [
        "orderCreationDate" => time(),
          "customerDetails" => [
              "phone" => "79953325612",
              "contact" => "Amon"
          ],
        "cartItems" => [
            "items" => [
                [
                    "positionId" => 1,
                    "name" => "Лупень",
                    "quantity" => [
                        "value" => 5,
                        "measure" => "шт."
                    ],
                    "itemPrice" => 200 * 100,
                    "itemCode" => 1006456
                ]
            ]
        ]
      ];`

**Comment by HamasakiBrain** [comment]
Прощу помочь)

**Comment by HamasakiBrain** [comment]
именно запросы с сайта не работают таким образом, а через приложение работает :\ 
в чем проблема может быть?)

**Comment by HamasakiBrain** [comment]
`"voronkovich/sberbank-acquiring-client": "^1.1",`

**Comment by voronkovich** [comment]
@HamasakiBrain, Выглядит вроде нормально. Может дело в том, что используется старая версия ОФД?
См. https://habr.com/en/post/433498/ и https://vk.com/@scienceandlive-sberbank-ffd-105

**Comment by HamasakiBrain** [comment]
> @HamasakiBrain, Выглядит вроде нормально. Может дело в том, что используется старая версия ОФД? См. https://habr.com/en/post/433498/ и https://vk.com/@scienceandlive-sberbank-ffd-105

Нужно просто добавить эти поля ?

**Comment by HamasakiBrain** [comment]
Добавил эти поля, все равно выдает ошибку 4, ОФД 1.5 стоит

**Comment by HamasakiBrain** [comment]
UPD: Решено, в 1.1 версии не конвертировалась корзина в json,
`json_encode([
         "carttems" => [
              "items" => $cartItems
          ]
      ])`
