### ISSUE TITLE
не возможно подключиться к эквайрингу сбера

### ISSUE THREAD

**Issue by Forspeed911** [voronkovich/sberbank-acquiring-client#27]
Добрый день.

С 01.02.2023 Сбер установил требования по использованию сертификата минцифры.
Теперь без них ваша библиотека не работает, даже если на машине все корректно установлено.

**Comment by kotyaro** [comment]
Все прекрасно работает после установки сертификатов минцифры

**Comment by voronkovich** [comment]
@kotyaro, благодарю за ответ!

Ещё можно попробовать изменить [настройки `curl`](https://www.php.net/manual/en/function.curl-setopt.php), чтобы проверка сертификата не проводилась:
- `CURLOPT_SSL_VERIFYPEER`
- `CURLOPT_SSL_VERIFYSTATUS`
- и т.д.

По крайней мере для тестов сойдёт.
