### ISSUE TITLE
Fiscal data support?

### ISSUE THREAD

**Issue by d9k** [voronkovich/sberbank-acquiring-client#4]
Do you plan to release fiscal data support?

Fiscal data is required for russian e-shops now, see http://54-fz.ru/

**Comment by voronkovich** [comment]
@d9k, No. Sberbank's API doesn't support this feature, so I can't implement it. See https://toster.ru/q/264846#comment_1430936

**Comment by d9k** [comment]
@voronkovich, thx, your answer in the thread by url are comprehensive.
I would post your code snippet here if you don't mind:

```
$result = $client->registerOrder($orderId, $orderAmount, $returnUrl, [
    'orderBundle' => [
        'cartItems' => [],
    ]
]);
```
