### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by syidev** [voronkovich/sberbank-acquiring-client#5]
Please, update PHPUnit tests to version 6.

**Comment by voronkovich** [comment]
@syidev, Why? The current version of this package (1.x) should support PHP 5.3 which is not supported by PHPUnit 6. I plan to release the new version (2.x) when PHP 5.6 reaches its end of life (31 Dec 2018 or earlier).

**Comment by syidev** [comment]
Thanks for the answer.
